# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call('_openmp_dmvnrm_arma', PACKAGE = 'openmp', x, mean, sigma, logd)
}

dmvnrm_arma_mc <- function(x, mean, sigma, logd = FALSE, cores = 1L) {
    .Call('_openmp_dmvnrm_arma_mc', PACKAGE = 'openmp', x, mean, sigma, logd, cores)
}

